### ISSUE TITLE
Error when capturing Seurat data in the default scene

### ISSUE THREAD

**Issue by clg236** [Powerbyte7/seurat_capture_addon#10]
Using Blender 2.9. After adding a capture box and moving the default cube away, I'm getting the error below. Any ideas?

```
Traceback (most recent call last):
  File "C:\Users\root\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\seurat_capture_addon-master\capture.py", line 73, in execute
    if self.check_for_intersections(context, capture_box_location, capture_box_scale):
  File "C:\Users\root\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\seurat_capture_addon-master\capture.py", line 195, in check_for_intersections
    distance=(b - a).length,
TypeError: Scene.ray_cast(): error with argument 1, "view_layer" -  Function.view_layer expected a ViewLayer type, not Depsgraph

location: <unknown location>:-1
```

**Comment by Powerbyte7** [comment]
Blender 2.91 made a small change to the raycast function, which broke the addon for older versions. I fixed it with ad9de8103ac1eb531a395977ac7d756beb367999, the addon should now work for versions 2.80 and above.
