### ISSUE TITLE
Not work

### ISSUE THREAD

**Issue by Rooster-Fighter** [Powerbyte7/seurat_capture_addon#9]
I'm noob.
This is error after create capture box and push capture data.
Is it support 2.83?
----------------------------
Traceback (most recent call last):
  File "C:\Users\XXX\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\seurat_capture_addon\capture.py", line 73, in execute
    if self.check_for_intersections(context, capture_box_location, capture_box_scale):
  File "C:\Users\XXX\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\seurat_capture_addon\capture.py", line 195, in check_for_intersections
    distance=(b - a).length,
TypeError: Scene.ray_cast(): error with argument 1, "view_layer" -  Function.view_layer expected a ViewLayer type, not Depsgraph

location: <unknown location>:-1

**Comment by Powerbyte7** [comment]
The addon currently isn't compatible with 2.83, only Blender versions above 2.90 are supported by the addon. I think it's possible to make it work with 2.83 by making a few changes, but I don't have the time to implement that right now.

**Comment by Rooster-Fighter** [comment]
Oh, I see!
No problem!  Thank you for reply!
I try on 2.90 :).
(i'm japanese sorry for bad english)
